{% set name = "seqnado" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: 1.0.2
source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/seqnado-{{ version }}.tar.gz
  sha256: 4b12e45e095eda896bbef8e006bf8b7a33d6141f470b7984f73061c3248f3ec7
build:
  number: 0
  noarch: python
  script_env:
  - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script: {{ PYTHON }} -m pip install . --no-deps -vvv
  entry_points:
  - seqnado = seqnado.cli:app
  run_exports:
  - {{ pin_subpackage('seqnado', max_pin="x.x") }}
requirements:
  host:
  - python >=3.10
  - setuptools >=61.0
  - wheel
  - setuptools-scm >=6.2
  - pip
  run:
  - python >=3.10
  - click<=8.3.1
  - cookiecutter<=2.6.0
  - numpy>=1.24,<=2.1.0
  - pandas>=2.0,<=2.3.3
  - pandera<=0.27.0
  - pexpect<=4.9.0
  - pip
  - pulp<=3.3.0
  - pydantic<=2.12.5
  - pyyaml<=6.0.3
  - rich<=14.2.0
  - seaborn<=0.13.2
  - snakemake-wrapper-utils<=0.8.0
  - snakemake>=9.12.0,<=9.14.5
  - tracknado>=0.3.1,<1.0.0
  - typer<=0.21.1
  - wget<=3.2
  - snakemake-executor-plugin-slurm<=2.0.3
test:
  imports:
  - seqnado
  commands:
  - seqnado --help
about:
  home: https://github.com/Milne-Group/SeqNado
  summary: 'A unified and user-friendly collection of pipelines for: ATAC-seq, ChIP-seq,
    CUT&RUN/TAG, RNA-seq, WGS, Methylation (Bisulphite/TAPS), CRISPR screens and Micro-Capture-C.'
  license: GPL-3.0-or-later
  license_file: LICENSE
extra:
  recipe-maintainers:
  - alsmith151
  - CChahrour
